### ISSUE TITLE
Donation form banner has unnecessary min-height

### ISSUE THREAD

**Issue by noahcooper** [convio/make-a-wish-luminate-framework#1]
In the [donation form banner](https://github.com/convio/make-a-wish-luminate-framework/blob/dev/html-includes/donation-form/banner.html), we're setting an inline style for `min-height` on `#divHeroWrapper`, and then later, we're also using JavaScript to set `min-height` on the same element.

Unless I'm missing something, this shouldn't be necessary, and we should remove the inline style and the JavaScript. Once we've done so, we should also remove the `id="divHeroWrapper"` attribute from the element, since that selector will no longer be used anywhere else.

**Comment by noahcooper** [comment]
@Blackbaud-NickGarcia can you take a look at this one?

**Comment by Blackbaud-NickGarcia** [comment]
Yeah definitely. I'll update once this is complete.

**Comment by noahcooper** [comment]
Thanks, looks great!
