### ISSUE TITLE
Inline styles on various elements

### ISSUE THREAD

**Issue by noahcooper** [convio/make-a-wish-luminate-framework#21]
We have some inline style attributes sprinkled throughout the HTML includes. We need to remove all of the inline styles, and move everything to its appropriate LESS file.

**Comment by Blackbaud-NickGarcia** [comment]
I think I've removed all the inline styles and added the CSS to the appropriate LESS file.

**Comment by noahcooper** [comment]
@Blackbaud-NickGarcia a search for the `style` attribute across the repo turns up just one remaining place you need to update:

[/html-includes/donation-form/form-repeater.html](/blob/dev/html-includes/donation-form/form-repeater.html)

``` html
<h5 class="ty-currency mobile-ty" style="float: right;">
  <span class="js--donation-amount-selected"></span>
</h5>
```
