### ISSUE TITLE
Direct your donation not working properly on IE 

### ISSUE THREAD

**Issue by rdewagan** [convio/make-a-wish-luminate-framework#22]
Direct your donation is showing up weird in IE. Please see screenshot below. National and Local buttons too large. 

Also Note: When going to International or Local in IE, the search bar within the local selector and international selector only allow you to type in 1 letter. After typing in 1 letter you cannot continue typing until you click back in the box. This occurs on all IE versions tested (8,9,10) 

Steps to reproduce: Select "Local" under direct your donation. Then try typing in California on the search bar for the local chapters dropdown. 

![qa direct your donation ie 11](https://cloud.githubusercontent.com/assets/13538898/9008124/8b908678-375d-11e5-973a-f179d4e47791.jpg)

**Comment by rdewagan** [comment]
This is also occurring when selecting International on IE. If you try and type in "Italy" into the International search, you can only type in 1 letter at a time and cannot continue typing until you click in the box again.

**Comment by noahcooper** [comment]
@rdewagan Can you ret-test the issue with not being able to type in the input in IE? I just tested and can't reproduce that. I wonder if we accidentally fixed this in another bug.

**Comment by noahcooper** [comment]
@Blackbaud-NickGarcia can you take care of the CSS issues in IE?

**Comment by rdewagan** [comment]
@Blackbaud-NickGarcia Tested on IE 11 and IE 10 and styling is correct for "direct your donation" buttons. Looking to test on IE 9. This can be closed out for now
