### ISSUE TITLE
Page 2 Donation form - zip code is not rendering city and state

### ISSUE THREAD

**Issue by rdewagan** [convio/make-a-wish-luminate-framework#24]
All browsers experiencing this issue.

Expected functionality is on the second page of the donation form under "your info" section when a user puts in a zip code, there is a city and state field that shows up based up on zip code (using the google maps API) 

Steps to create: 

Go through 1st page of donation form as normal
Put in information under "your info" section. 
Then put in a zip code. 
No state and city fields show up when entering a zip code

**Comment by noahcooper** [comment]
Fixed.

**Comment by noahcooper** [comment]
Fixed.
