### ISSUE TITLE
(Mobile) Direct your donation chapter selector

### ISSUE THREAD

**Issue by rdewagan** [convio/make-a-wish-luminate-framework#25]
Chapter selector for direct your donation on mobile is in the incorrect location. 

Steps to reproduce on mobile:
1.) Enter in information on first page of donation form 
2.) In the direct your donation section, select "Local" 
3.) The drop down chapter selector needs to be below "local". Currently it is showing up below "International".

**Comment by rdewagan** [comment]
Attaching screenshot. 
![mobile - state selector](https://cloud.githubusercontent.com/assets/13538898/9037426/e34d655c-39b0-11e5-861c-4f323f4c65d3.PNG)

**Comment by noahcooper** [comment]
Fixed.
