### ISSUE TITLE
(Mobile) Credit card expiration date and year and CVV

### ISSUE THREAD

**Issue by rdewagan** [convio/make-a-wish-luminate-framework#26]
The credit card expiration date and field are showing up differently than the approved PSD files. 

Expiration date and year should be side by side, but rather on mobile are showing up one after the other. 

Steps to reproduce: 

1.) Go through page 1 of the donation form providing information 
2.) Scroll down to "your billing info" section 
3.) View Expiration date section. 
4.) First the expiration date drop down selector is there (whole width of mobile device), then there is the year selector. 
5.) CVV needs to be a shorter box, and "whats this?" link needs to be to the right hand side. 

![mobile - credit card exp date and cvv](https://cloud.githubusercontent.com/assets/13538898/9037415/c1146c1a-39b0-11e5-87ea-6a5cba386f16.PNG)

**Comment by noahcooper** [comment]
Fixed.
