### ISSUE TITLE
(Mobile) Thank you page wrapper and social media links 

### ISSUE THREAD

**Issue by rdewagan** [convio/make-a-wish-luminate-framework#27]
Steps to reproduce: 

1.) On mobile go to : https://secure2.convio.net/wishdev/site/SPageServer/?pagename=donate_thanks
2.) The wrapper of this page still has the "donate" button the right hand side. According to the PSD, there should be no donate button on mobile.  See screenshot below 
3.) When you scroll down below the video the facebook and twittter share icons on 2 small square boxes. They should be like the PSD file and should be displayed as "share" and "tweet" Screenshot below 

![mobile - thank you page header and social links](https://cloud.githubusercontent.com/assets/13538898/9037844/da710b2e-39b4-11e5-9d37-f80d5aa55d54.PNG)

**Comment by noahcooper** [comment]
@rdewagan I actually made the Donate button show up on purpose. We had a conversation with Make-a-Wish about this after the designs were finalized (I believe during the meeting where we reviewed the Technical Specification Doc), and the consensus was that while it doesn't make sense to link people to the form when they're already on it, it does make sense to have the button on the thank you page on the off chance the donor wants to make a second donation.

**Comment by rdewagan** [comment]
@noahcooper thanks for refreshing my memory, I actually do remember discussing that with them. Disregard this issue. Only issue remaining is social media share links

**Comment by Blackbaud-NickGarcia** [comment]
@rdewagan I think the styling issues have been fixed. Could you check it out and let me know if this issue can be closed?

**Comment by rdewagan** [comment]
@Blackbaud-NickGarcia re-test. Functionality is now correct. Issue can be closed
