### ISSUE TITLE
(Tablet) "Direct your donation" -  Local option 

### ISSUE THREAD

**Issue by rdewagan** [convio/make-a-wish-luminate-framework#28]
Local button for "direct your donation" on tablet is rendering a little off. See screenshot below. 

![tablet - direct your donatoin local button](https://cloud.githubusercontent.com/assets/13538898/9038575/e53d3126-39ba-11e5-9311-66cb6cc54319.PNG)

**Comment by noahcooper** [comment]
Fixed.
