### ISSUE TITLE
(Mobile + Tablet) Your info section - city and state fields not hidden

### ISSUE THREAD

**Issue by rdewagan** [convio/make-a-wish-luminate-framework#29]
City and state fields are not appearing hidden as with Desktop. 

Steps to reproduce. 

1.) On a mobile or tablet device, go to the donation form and enter in information on the first page. 
2.) Once on the 2nd page scroll down to "your info" section. 
3.) Currently fields are showing for zip code, city and state. 
4.) Expected functionality is that city and state are hidden fields, and when a user puts in their zip code the city and state field show up populated based upon the zip code entered. 

Screenshot below. 

![mobile tablet - you info section state city fields not hidden](https://cloud.githubusercontent.com/assets/13538898/9038845/0bd132cc-39bd-11e5-90f0-f7eb9b49c7ef.PNG)

**Comment by noahcooper** [comment]
Fixed.

**Comment by rdewagan** [comment]
@noahcooper - One thing to note on this that I just found and I think WISH will ask for. Once a zip code is entered city/state fields show up and are populated correctly. However if you delete your zip code, the city/state fields remain populated with the original zip code entered. 

May be a special use case but they may want those fields to be hidden if the zip code is deleted?
