### ISSUE TITLE
(Tablet) "Your donation" section rendering incorrectly 

### ISSUE THREAD

**Issue by rdewagan** [convio/make-a-wish-luminate-framework#30]
When visiting the "Your donation" section on a tablet, the formatting looks off. Donation amount is getting cut off along with the review/edit button being in the incorrect location. Steps to reproduce below. 

1.) On a tablet device go through the first page of the donation form 
2.) Once on the second page review the "your donation" section and see issues. 

Screenshot below. 

![tablet - your donation section](https://cloud.githubusercontent.com/assets/13538898/9039103/b3f08880-39be-11e5-8044-a4d375b4d532.PNG)

**Comment by noahcooper** [comment]
Fixed.
