### ISSUE TITLE
(Tablet) - thank you page styling

### ISSUE THREAD

**Issue by rdewagan** [convio/make-a-wish-luminate-framework#31]
Thank you page on tablet does not represent the approved design. 

Steps to reproduce: 

1.) Go to thank you page link on tablet : https://secure2.convio.net/wishdev/site/SPageServer/?pagename=donate_thanks

2.) text is on top and share links are below.
3.) below all text is the video. 

Expected functionality: 

1.) Similar to desktop text and share icons should be on left hand side, and video should be on the right hand side. 

Screenshots below for tablet. 

![tablet - thank you page](https://cloud.githubusercontent.com/assets/13538898/9040077/48c41af2-39c5-11e5-979c-e91c7a1f4bf7.PNG)

**Comment by Blackbaud-NickGarcia** [comment]
@rdewagan I think I've made the styling updates to this issue. Could you check it out and let me know if we can close it?

**Comment by rdewagan** [comment]
@Blackbaud-NickGarcia re-tested. Expected functionality is now correct. Only issue is video seems slightly small. on page. Screenshot below.  Not a high priority item right now. 

![tablet - thank you page 2 0](https://cloud.githubusercontent.com/assets/13538898/9171367/81fabf90-3f30-11e5-886e-a26bd7cf3807.PNG)

**Comment by noahcooper** [comment]
@Blackbaud-NickGarcia can you move the inline style on `.addthis_toolbox` to thank-you.less?
