### ISSUE TITLE
Each step should be validated when submitted

### ISSUE THREAD

**Issue by noahcooper** [convio/make-a-wish-luminate-framework#33]
When step 1 is submitted, the form should validate:

1) That there is a valid donation amount
2) That all required honor/memorial fields are valid if making a tribute gift
3) That donor intent is not null

When step 2 is submitted, the form should validate:

1) That all required donor fields are valid
2) That Company Name has a value if making a company gift
3) That all required billing fields are valid if entering a different billing address
4) That all credit card fields are valid if making a credit card gift

Fields in error should be highlighted in red, and the form should scroll to the first field in error.

**Comment by rdewagan** [comment]
Noah one more validation for page 1: card design needs to be a required as well. Currently a user can go through the whole donation form without choosing a card design.

**Comment by rdewagan** [comment]
On Page 2: if user selects "donate on behalf of company" this needs to be required field. Currently if a user selects "donate on behalf of company" and leaves the field blank, they are still able to submit a donation

**Comment by noahcooper** [comment]
Both of those issues should now be fixed.
