### ISSUE TITLE
Local chapter issue - every browser

### ISSUE THREAD

**Issue by rdewagan** [convio/make-a-wish-luminate-framework#34]
When making a donation to a chapter the correct security category is not being attributed within LO. 

Steps to Reproduce: 

1.) Start at http://wishdev.convio.net/site/PageServer?pagename=donate_now
2.) Fill in all information and at "direct your donation" select Make-a-wish Texas Gulf Coast & Louisiana 
3.) Complete donation. 
4.) Log into LO and go to cons 360. 
5.) Search for record that was just created and see attributed security category. (Screenshots attached below) 

![all browsers - security category 1](https://cloud.githubusercontent.com/assets/13538898/9305355/6cbe139e-44b6-11e5-8869-e1f026641e2c.png)
![all browsers - security category 2](https://cloud.githubusercontent.com/assets/13538898/9305357/6ccba6b2-44b6-11e5-973a-a4d8e19d77e6.png)
![all browsers - security category 3](https://cloud.githubusercontent.com/assets/13538898/9305356/6cc383a6-44b6-11e5-9e6d-cb1d3d87c8b9.png)

**Comment by noahcooper** [comment]
Fixed.
