### ISSUE TITLE
All Browsers - Incomplete email address 

### ISSUE THREAD

**Issue by rdewagan** [convio/make-a-wish-luminate-framework#35]
When going through the donation form and typing in an incomplete email address,  no error message is produced. Instead the transactions processing page shows up and does not go away. 

Steps to reproduce: 

1.) Fill out page 1 of donation form
2.) On second page fill out all information, except in the email address section type in "raj.dewagan@blackbaud" without the .com 
3.) Fill out credit card information and click submit. 
4.) Transaction processing screen appears and hangs, but does not actually complete the transaction. (screenshot below) 

![all browsers - incomplete email address 1](https://cloud.githubusercontent.com/assets/13538898/9305479/52596476-44b7-11e5-87ea-41dce6491267.png)
![all browsers - incomplete email address 2](https://cloud.githubusercontent.com/assets/13538898/9305480/526323da-44b7-11e5-9386-b076bf205f05.png)

**Comment by noahcooper** [comment]
This is expected per the HTML standard:

``` html
This requirement is a willful violation of RFC 5322, which defines a syntax for e-mail addresses that is simultaneously too strict (before the "@" character), too vague (after the "@" character), and too lax (allowing comments, whitespace characters, and quoted strings in manners unfamiliar to most users) to be of practical use here.
```

We'll need to write our own custom validation method to workaround the spec.

**Comment by noahcooper** [comment]
Fixed.
