### ISSUE TITLE
All Browsers - "Other" donation amount is not functioning correctly

### ISSUE THREAD

**Issue by rdewagan** [convio/make-a-wish-luminate-framework#38]
When selecting an amount that is "other" there are several problems. Steps to reproduce below. 

1.) Start at  http://wishdev.convio.net/site/PageServer?pagename=donate_now
2.)  Select "other" amount and enter 5 
3.) Click save and continue 
4.) Your donation section only has a 5. Does not show "$" like other donation amounts. Screenshot below 

![selecting other donation amount - page 2](https://cloud.githubusercontent.com/assets/13538898/9311627/feb09116-44dc-11e5-93c6-8893a978a057.JPG)

**Comment by rdewagan** [comment]
When processing donation....thank you page shows $1, even though user entered 5 in the donation amount

**Comment by rdewagan** [comment]
Back-end LO also shows $1 when selecting $5. See screenshot below 

![other donation amount - lo cons profile](https://cloud.githubusercontent.com/assets/13538898/9312479/83bc8932-44e2-11e5-9f22-07a9d9c06c86.JPG)

**Comment by noahcooper** [comment]
Fixed.
