### ISSUE TITLE
All browsers - donate monthly link 

### ISSUE THREAD

**Issue by rdewagan** [convio/make-a-wish-luminate-framework#39]
When selecting donate monthly and clicking on the link "Learn more about out monthly donor program and benefits" the link goes nowhere. 

Expected functionality - to be a message that shows up in a pop up box as being currently used on wish.org 

https://secure2.wish.org/site/SPageServer?pagename=donate&chid=100-000

**Comment by noahcooper** [comment]
Fixed.
