### ISSUE TITLE
The donation form intro copy currently uses placeholder text

### ISSUE THREAD

**Issue by noahcooper** [convio/make-a-wish-luminate-framework#4]
The intro currently reads "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea."

We need real copy from Make-a-Wish.

**Comment by noahcooper** [comment]
@rdewagan do you want to follow up with the client about what the real copy for the intro should be?

**Comment by rdewagan** [comment]
@noahcooper Followed up with client and gave deadline of Friday 7/31 to  get us that text by so we can put it into the donation form presentation on 8/3

**Comment by rdewagan** [comment]
@noahcooper For testing purposes client would like to have content below added in this area. 

“Thank you for your support of Make-A-Wish®. Your donation will help us grant more wishes that transform the lives of kids with life-threatening medical conditions, forever.”
