### ISSUE TITLE
All browsers - Donate button in header

### ISSUE THREAD

**Issue by rdewagan** [convio/make-a-wish-luminate-framework#40]
Currently clicking the donate button in the header is directing to the live donation form. 

For testing purposes we should have that donate button revert back to the first page of the donation form we created. (ie. clicking donate in the header should lead to https://secure2.convio.net/wishdev/site/SPageServer/?pagename=donate_now)

**Comment by noahcooper** [comment]
This is expected -- the Donate button links to the current form, which will dynamically redirect to the new form through whatever A/B testing software Make-a-Wish is using.

Is the request just to temporarily link to the new form during UAT?

**Comment by rdewagan** [comment]
I will confirm with the client. 

Thank you for the confirmation

**Comment by rdewagan** [comment]
Client confirmed they understand that this is expected functionality. No changes need to be made at this point.
