### ISSUE TITLE
Credit card validation 

### ISSUE THREAD

**Issue by rdewagan** [convio/make-a-wish-luminate-framework#41]
Tying this to #33 

When you type in an incorrect credit card number such as "1111-1111-1111-1111" and an invalid expiration date (ie date in the past) and an invalid CVV then click submit donation...donation processing popup shows up and then goes away. There is no error mentioning that the credit card info is incorrect. 

Expected functionality: having and error message or validation letting user know that the credit card number is wrong or cvv/expiration date is wrong.

**Comment by noahcooper** [comment]
Fixed.
