### ISSUE TITLE
All browsers - CVV "whats this" link

### ISSUE THREAD

**Issue by rdewagan** [convio/make-a-wish-luminate-framework#42]
CVV "whats this" link is currently not linking to the correct area. Needs to link to the same page as wish.org current donation form is linking too. 

![cvv - whats this link](https://cloud.githubusercontent.com/assets/13538898/9347378/75fd3b86-45ee-11e5-9109-9a78d5b607b1.JPG)

**Comment by noahcooper** [comment]
Fixed.
