### ISSUE TITLE
Desktop/Tablet - Thank you page: print receipt button

### ISSUE THREAD

**Issue by rdewagan** [convio/make-a-wish-luminate-framework#43]
Currently the print receipt button is not working on Desktop and Tablet. 

Unsure what the expected functionality is once clicking the print receipt button. Is it intended to bring up a new webpage with a printable receipt? 

*Mobile does not have the functionality to print receipt

**Comment by noahcooper** [comment]
Fixed. Clicking the Print Receipt button should now bring up the print dialog for your machine.
