### ISSUE TITLE
All browsers - "Donate on behalf of company" field

### ISSUE THREAD

**Issue by rdewagan** [convio/make-a-wish-luminate-framework#44]
On all browsers, the "company name" label is collapsing the entire field. 

Steps to reproduce: 

1.) Start at http://wishdev.convio.net/site/PageServer?pagename=donate_now
2.) Go to the 2nd page of the donation form 
3.) In the "your info" section check the box that says "donate on behalf of a company" 
4.) Click on "company name" 
5.) This unchecks the "donate on behalf of company" field and collapses it.

**Comment by noahcooper** [comment]
Fixed.

**Comment by noahcooper** [comment]
Fixed.
