### ISSUE TITLE
Form ID designation is incorrect 

### ISSUE THREAD

**Issue by rdewagan** [convio/make-a-wish-luminate-framework#45]
On the dev site the client created a new user through a test donation. 

First Name: Mawfa
Last Name: Test345
Email: mawfa.test+newform5@gmail.com

The donation was designated to Alaska Washington (UR-048-01). When looking in LO on the interactions tab for this user, the metadata was recorded as Fund ID UR-100-01 which is the national designation. 

Sign into LO -> Cons 360 (search for user above) --> Interactions tab --> Scroll down and click on donation interaction "Make-A-Wish Alaska and Washington" --> see "foreign_key2"

**Comment by noahcooper** [comment]
Currently the value for foreign_key2 is being set at the time the page loads, based on the chid URL parameter. Looking at the old donation form, it looks like the value needs to be set each time the donor intent is changed.

**Comment by noahcooper** [comment]
Fixed.
