### ISSUE TITLE
URL redirects functionality

### ISSUE THREAD

**Issue by rdewagan** [convio/make-a-wish-luminate-framework#46]
Client had done URL override test cases to go update the URL so that it reflects their "donate_now" form (new donation form), and noticed that the levels are not working. Expectation is that all these override codes to work on the new donation form. 

Current donation form with level override (working): 

https://secure2.convio.net/wishdev/site/SPageServer?pagename=donate&level1=123&level2=456&level3=789

New donation form with level override (not working) 

https://secure2.convio.net/wishdev/site/SPageServer/?pagename=donate_now&level1=123&level2=456&level3=789

Amanda confirmed that the level1, level2 etc. overrides need to work

**Comment by noahcooper** [comment]
Fixed.
