### ISSUE TITLE
The logo in the wrapper header should be dynamic based on the value of a session variable named chid

### ISSUE THREAD

**Issue by noahcooper** [convio/make-a-wish-luminate-framework#7]
Right now the logo in the header is hardcoded to use the national logo. It should be dynamic based on chid, so that if a donor comes to the form from a specific chapter's website, that chapter's logo is displayed.

**Comment by rdewagan** [comment]
Noah is there a way to test this?

**Comment by noahcooper** [comment]
To test this, you just need to toggle the chid in the URL, e.g.

http://wishdev.convio.net/site/PageServer?pagename=donate_now
http://wishdev.convio.net/site/PageServer?pagename=donate_now&chid=100-000
http://wishdev.convio.net/site/PageServer?pagename=donate_now&chid=016-000
