### ISSUE TITLE
Local chapter selection should use an input/dropdown combo using Select2

### ISSUE THREAD

**Issue by noahcooper** [convio/make-a-wish-luminate-framework#9]
The local chapter field in the [donor intent](https://github.com/convio/make-a-wish-luminate-framework/blob/dev/html-includes/donation-form/donor-intent.html) section is currently just a dropdown. The intention is for the field to use [Select2](https://select2.github.io/).

From the Technical Specification Doc:

```
If a donor chooses Local, a panel with a list of chapters to
donate to will be revealed (using slide down). The chapter list
will be presented as a combo input/dropdown using Select2.
```

**Comment by noahcooper** [comment]
@Blackbaud-NickGarcia can you take a look at this one?

**Comment by noahcooper** [comment]
@Blackbaud-NickGarcia I've added all of the options to the Select2 dropdown, so now it should just be a matter of you styling it to match the Make-a-Wish styles for <select>.

**Comment by Blackbaud-NickGarcia** [comment]
@noahcooper I've updated the dropdown. I'm not sure how it's supposed to look so I made it look as basic as possible.
